---
  - name: PLAY - FILE COPY
    hosts: all
    gather_facts: no
    connection: local

    tasks:
      - name: ENSURE FILES ARE ON REMOTE DEVICES
        ntc_file_copy:
          local_file=../CONFIGS/{{ inventory_hostname }}.conf
          platform={{ net_platform }}
          host={{ inventory_hostname }}
          username={{ un }}
          password={{ pwd }}
